modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/bettermolecularassembler/issues"

[[mixins]]
config="mixins.bettermolecularassembler.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
# updateJSONURL=""
description='''${mod_description}'''
authors="${mod_authors}"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2"
type="required"
versionRange="[19.2.17,20.0.0)"
ordering="AFTER"
side="BOTH"
